#!/usr/bin/env python
# -*- coding: utf-8 -*-

__license__   = 'GPL v3'
__copyright__ = '2021, un_pogaz <un.pogaz@gmail.com>'
__docformat__ = 'restructuredtext en'


try:
    load_translations()
except NameError:
    pass # load_translations() added in calibre 1.9

from collections import OrderedDict

# The following MARC Code associated name and decriptions are extracted from the https://github.com/Sigil-Ebook/Sigil code source (with minor edit)
# Some translation are also based on the work done for Sigil, see CREDITS file

# For the authoritiative relator list and descriptive definitions see http://www.loc.gov/marc/relators/

t = _("//// MARC CONTRIBUTORS ROLES")
# https://www.loc.gov/marc/relators/relacode.html
CONTRIBUTORS_ROLES = OrderedDict([
    ("", ""),
    ("abr", _("Abridger")),
    ("act", _("Actor")),
    ("adp", _("Adapter")),
    ("anl", _("Analyst")),
    ("anm", _("Animator")),
    ("ann", _("Annotator")),
    ("apl", _("Appellant")),
    ("ape", _("Appellee")),
    ("app", _("Applicant")),
    ("arc", _("Architect")),
    ("arr", _("Arranger")),
    ("acp", _("Art copyist")),
    ("adi", _("Art director")),
    ("art", _("Artist")),
    ("ard", _("Artistic director")),
    ("asg", _("Assignee")),
    ("asn", _("Associated name")),
    ("att", _("Attributed name")),
    ("auc", _("Auctioneer")),
    ("aut", _("Author")),
    ("aqt", _("Author in quotations or text extracts")),
    ("aft", _("Author of afterword, colophon, etc.")),
    ("aud", _("Author of dialog")),
    ("aui", _("Author of introduction, etc.")),
    ("aus", _("Author of screenplay, etc.")),
    ("ato", _("Autographer")),
    ("ant", _("Bibliographic antecedent")),
    ("bnd", _("Binder")),
    ("bdd", _("Binding designer")),
    ("blw", _("Blurb writer")),
    ("bkd", _("Book designer")),
    ("bkp", _("Book producer")),
    ("bjd", _("Bookjacket designer")),
    ("bpd", _("Bookplate designer")),
    ("bsl", _("Bookseller")),
    ("brl", _("Braille embosser")),
    ("brd", _("Broadcaster")),
    ("cll", _("Calligrapher")),
    ("ctg", _("Cartographer")),
    ("cas", _("Caster")),
    ("cns", _("Censor")),
    ("chr", _("Choreographer")),
    ("cng", _("Cinematographer")),
    ("cli", _("Client")),
    ("cor", _("Collection registrar")),
    ("col", _("Collector")),
    ("clt", _("Collotyper")),
    ("clr", _("Colorist")),
    ("cmm", _("Commentator")),
    ("cwt", _("Commentator for written text")),
    ("com", _("Compiler")),
    ("cpl", _("Complainant")),
    ("cpt", _("Complainant-appellant")),
    ("cpe", _("Complainant-appellee")),
    ("cmp", _("Composer")),
    ("cmt", _("Compositor")),
    ("ccp", _("Conceptor")),
    ("cnd", _("Conductor")),
    ("con", _("Conservator")),
    ("csl", _("Consultant")),
    ("csp", _("Consultant to a project")),
    ("cos", _("Contestant")),
    ("cot", _("Contestant-appellant")),
    ("coe", _("Contestant-appellee")),
    ("cts", _("Contestee")),
    ("ctt", _("Contestee-appellant")),
    ("cte", _("Contestee-appellee")),
    ("ctr", _("Contractor")),
    ("ctb", _("Contributor")),
    ("cpc", _("Copyright claimant")),
    ("cph", _("Copyright holder")),
    ("crr", _("Corrector")),
    ("crp", _("Correspondent")),
    ("cst", _("Costume designer")),
    ("cou", _("Court governed")),
    ("crt", _("Court reporter")),
    ("cov", _("Cover designer")),
    ("cre", _("Creator")),
    ("cur", _("Curator of an exhibition")),
    ("dnc", _("Dancer")),
    ("dtc", _("Data contributor")),
    ("dtm", _("Data manager")),
    ("dte", _("Dedicatee")),
    ("dto", _("Dedicator")),
    ("dfd", _("Defendant")),
    ("dft", _("Defendant-appellant")),
    ("dfe", _("Defendant-appellee")),
    ("dgg", _("Degree grantor")),
    ("dln", _("Delineator")),
    ("dpc", _("Depicted")),
    ("dpt", _("Depositor")),
    ("dsr", _("Designer")),
    ("drt", _("Director")),
    ("dis", _("Dissertant")),
    ("dbp", _("Distribution place")),
    ("dst", _("Distributor")),
    ("dnr", _("Donor")),
    ("drm", _("Draftsman")),
    ("dub", _("Dubious author")),
    ("edt", _("Editor")),
    ("edc", _("Editor of compilation")),
    ("edm", _("Editor of moving image work")),
    ("elg", _("Electrician")),
    ("elt", _("Electrotyper")),
    ("eng", _("Engineer")),
    ("egr", _("Engraver")),
    ("etr", _("Etcher")),
    ("evp", _("Event place")),
    ("exp", _("Expert")),
    ("fac", _("Facsimilist")),
    ("fld", _("Field director")),
    ("fmd", _("Film director")),
    ("fds", _("Film distributor")),
    ("flm", _("Film editor")),
    ("fmp", _("Film producer")),
    ("fmk", _("Filmmaker")),
    ("fpy", _("First party")),
    ("frg", _("Forger")),
    ("fmo", _("Former owner")),
    ("fnd", _("Funder")),
    ("gis", _("Geographic information specialist")),
    ("hnr", _("Honoree")),
    ("hst", _("Host")),
    ("his", _("Host institution")),
    ("ilu", _("Illuminator")),
    ("ill", _("Illustrator")),
    ("ins", _("Inscriber")),
    ("itr", _("Instrumentalist")),
    ("ive", _("Interviewee")),
    ("ivr", _("Interviewer")),
    ("inv", _("Inventor")),
    ("isb", _("Issuing body")),
    ("jud", _("Judge")),
    ("jug", _("Jurisdiction governed")),
    ("lbr", _("Laboratory")),
    ("ldr", _("Laboratory director")),
    ("lsa", _("Landscape architect")),
    ("led", _("Lead")),
    ("len", _("Lender")),
    ("lil", _("Libelant")),
    ("lit", _("Libelant-appellant")),
    ("lie", _("Libelant-appellee")),
    ("lel", _("Libelee")),
    ("let", _("Libelee-appellant")),
    ("lee", _("Libelee-appellee")),
    ("lbt", _("Librettist")),
    ("lse", _("Licensee")),
    ("lso", _("Licensor")),
    ("lgd", _("Lighting designer")),
    ("ltg", _("Lithographer")),
    ("lyr", _("Lyricist")),
    ("mfp", _("Manufacture place")),
    ("mfr", _("Manufacturer")),
    ("mrb", _("Marbler")),
    ("mrk", _("Markup editor")),
    ("med", _("Medium")),
    ("mdc", _("Metadata contact")),
    ("mte", _("Metal-engraver")),
    ("mtk", _("Minute taker")),
    ("mod", _("Moderator")),
    ("mon", _("Monitor")),
    ("mcp", _("Music copyist")),
    ("msd", _("Musical director")),
    ("mus", _("Musician")),
    ("nrt", _("Narrator")),
    ("osp", _("Onscreen presenter")),
    ("opn", _("Opponent")),
    ("orm", _("Organizer of meeting")),
    ("org", _("Originator")),
    ("oth", _("Other")),
    ("own", _("Owner")),
    ("pan", _("Panelist")),
    ("ppm", _("Papermaker")),
    ("pta", _("Patent applicant")),
    ("pth", _("Patent holder")),
    ("pat", _("Patron")),
    ("prf", _("Performer")),
    ("pma", _("Permitting agency")),
    ("pht", _("Photographer")),
    ("ptf", _("Plaintiff")),
    ("ptt", _("Plaintiff-appellant")),
    ("pte", _("Plaintiff-appellee")),
    ("plt", _("Platemaker")),
    ("pra", _("Praeses")),
    ("pre", _("Presenter")),
    ("prt", _("Printer")),
    ("pop", _("Printer of plates")),
    ("prm", _("Printmaker")),
    ("prc", _("Process contact")),
    ("pro", _("Producer")),
    ("prn", _("Production company")),
    ("prs", _("Production designer")),
    ("pmn", _("Production manager")),
    ("prd", _("Production personnel")),
    ("prp", _("Production place")),
    ("prg", _("Programmer")),
    ("pdr", _("Project director")),
    ("pfr", _("Proofreader")),
    ("prv", _("Provider")),
    ("pup", _("Publication place")),
    ("pbl", _("Publisher")),
    ("pbd", _("Publishing director")),
    ("ppt", _("Puppeteer")),
    ("rdd", _("Radio director")),
    ("rpc", _("Radio producer")),
    ("rcp", _("Recipient")),
    ("rce", _("Recording engineer")),
    ("rce", _("Recording engineer")),
    ("red", _("Redactor")),
    ("ren", _("Renderer")),
    ("rpt", _("Reporter")),
    ("rps", _("Repository")),
    ("rth", _("Research team head")),
    ("rtm", _("Research team member")),
    ("res", _("Researcher")),
    ("rsp", _("Respondent")),
    ("rst", _("Respondent-appellant")),
    ("rse", _("Respondent-appellee")),
    ("rpy", _("Responsible party")),
    ("rsg", _("Restager")),
    ("rsr", _("Restorationist")),
    ("rev", _("Reviewer")),
    ("rbr", _("Rubricator")),
    ("sce", _("Scenarist")),
    ("sad", _("Scientific advisor")),
    ("scr", _("Scribe")),
    ("scl", _("Sculptor")),
    ("spy", _("Second party")),
    ("sec", _("Secretary")),
    ("sll", _("Seller")),
    ("std", _("Set designer")),
    ("stg", _("Setting")),
    ("sgn", _("Signer")),
    ("sng", _("Singer")),
    ("sds", _("Sound designer")),
    ("spk", _("Speaker")),
    ("spn", _("Sponsor")),
    ("sgd", _("Stage director")),
    ("stm", _("Stage manager")),
    ("stn", _("Standards body")),
    ("str", _("Stereotyper")),
    ("stl", _("Storyteller")),
    ("sht", _("Supporting host")),
    ("srv", _("Surveyor")),
    ("tch", _("Teacher")),
    ("tcd", _("Technical director")),
    ("tld", _("Television director")),
    ("tlp", _("Television producer")),
    ("ths", _("Thesis advisor")),
    ("trc", _("Transcriber")),
    ("trl", _("Translator")),
    ("tyd", _("Type designer")),
    ("tyg", _("Typographer")),
    ("uvp", _("University place")),
    ("vdg", _("Videographer")),
    ("vac", _("Voice actor")),
    ("wit", _("Witness")),
    ("wde", _("Wood-engraver")),
    ("wdc", _("Woodcutter")),
    ("wam", _("Writer of accompanying material")),
    ("wac", _("Writer of added commentary")),
    ("wal", _("Writer of added lyrics")),
    ("wat", _("Writer of added text")),
    ("win", _("Writer of introduction")),
    ("wpr", _("Writer of preface")),
    ("wst", _("Writer of supplementary textual content"))
])

t = _("//// MARC CONTRIBUTORS DESCRIPTION")
#https://www.loc.gov/marc/relators/relaterm.html
CONTRIBUTORS_DESCRIPTION = OrderedDict([
    ("abr" , _("A person, family, or organization contributing to a resource by shortening or condensing the original work but leaving the nature and content of the original work substantially unchanged. For substantial modifications that result in the creation of a new work, see Author.") ),
    ("act" , _("Use for a person or organization who principally exhibits acting skills in a musical or dramatic presentation or entertainment.") ),
    ("adp" , _("Use for a person or organization who 1) reworks a musical composition, usually for a different medium, or 2) rewrites novels or stories for motion pictures or other audiovisual medium.") ),
    ("anl" , _("Use for a person or organization that reviews, examines and interprets data or information in a specific area.") ),
    ("anm" , _("Use for a person or organization who draws the two-dimensional figures, manipulates the three dimensional objects and/or also programs the computer to move objects and images for the purpose of animated film processing. Animation cameras, stands, celluloid screens, transparencies and inks are some of the tools of the animator.") ),
    ("ann" , _("Use for a person who writes manuscript annotations on a printed item.") ),
    ("apl" , _("A person or organization who appeals a lower court's decision.") ),
    ("ape" , _("A person or organization against whom an appeal is taken.") ),
    ("app" , _("Use for a person or organization responsible for the submission of an application or who is named as eligible for the results of the processing of the application (e.g., bestowing of rights, reward, title, position).") ),
    ("arc" , _("Use for a person or organization who designs structures or oversees their construction.") ),
    ("arr" , _("Use for a person or organization who transcribes a musical composition, usually for a different medium from that of the original; in an arrangement the musical substance remains essentially unchanged.") ),
    ("acp" , _("Use for a person (e.g., a painter or sculptor) who makes copies of works of visual art.") ),
    ("adi" , _("A person contributing to a motion picture or television production by overseeing the artists and craftspeople who build the sets.") ),
    ("art" , _("Use for a person (e.g., a painter) or organization who conceives, and perhaps also implements, an original graphic design or work of art, if specific codes (e.g., [egr], [etr]) are not desired. For book illustrators, prefer Illustrator [ill].") ),
    ("ard" , _("Use for a person responsible for controlling the development of the artistic style of an entire production, including the choice of works to be presented and selection of senior production staff.") ),
    ("asg" , _("Use for a person or organization to whom a license for printing or publishing has been transferred.") ),
    ("asn" , _("Use for a person or organization associated with or found in an item or collection, which cannot be determined to be that of a Former owner [fmo] or other designated relator indicative of provenance.") ),
    ("att" , _("Use for an author, artist, etc., relating him/her to a work for which there is or once was substantial authority for designating that person as author, creator, etc. of the work.") ),
    ("auc" , _("Use for a person or organization in charge of the estimation and public auctioning of goods, particularly books, artistic works, etc.") ),
    ("aut" , _("Use for a person or organization chiefly responsible for the intellectual or artistic content of a work, usually printed text. This term may also be used when more than one person or body bears such responsibility.") ),
    ("aqt" , _("Use for a person or organization whose work is largely quoted or extracted in works to which he or she did not contribute directly. Such quotations are found particularly in exhibition catalogs, collections of photographs, etc.") ),
    ("aft" , _("Use for a person or organization responsible for an afterword, postface, colophon, etc. but who is not the chief author of a work.") ),
    ("aud" , _("Use for a person or organization responsible for the dialog or spoken commentary for a screenplay or sound recording.") ),
    ("aui" , _("Use for a person or organization responsible for an introduction, preface, foreword, or other critical introductory matter, but who is not the chief author.") ),
    ("aus" , _("Use for a person or organization responsible for a motion picture screenplay, dialog, spoken commentary, etc.") ),
    ("ato" , _("A person whose manuscript signature appears on an item.") ),
    ("ant" , _("Use for a person or organization responsible for a work upon which the work represented by the catalog record is based. This may be appropriate for adaptations, sequels, continuations, indexes, etc.") ),
    ("bnd" , _("Use for a person or organization responsible for the binding of printed or manuscript materials.") ),
    ("bdd" , _("Use for a person or organization responsible for the binding design of a book, including the type of binding, the type of materials used, and any decorative aspects of the binding.") ),
    ("blw" , _("A person or organization responsible for writing a commendation or testimonial for a work, which appears on or within the publication itself, frequently on the back or dust jacket of print publications or on advertising material for all media.") ),
    ("bkd" , _("Use for a person or organization responsible for the entire graphic design of a book, including arrangement of type and illustration, choice of materials, and process used.") ),
    ("bkp" , _("Use for a person or organization responsible for the production of books and other print media, if specific codes (e.g., [bkd], [egr], [tyd], [prt]) are not desired.") ),
    ("bjd" , _("Use for a person or organization responsible for the design of flexible covers designed for or published with a book, including the type of materials used, and any decorative aspects of the bookjacket.") ),
    ("bpd" , _("Use for a person or organization responsible for the design of a book owner's identification label that is most commonly pasted to the inside front cover of a book.") ),
    ("bsl" , _("Use for a person or organization who makes books and other bibliographic materials available for purchase. Interest in the materials is primarily lucrative.") ),
    ("brl" , _("A person, family, or organization involved in manufacturing a resource by embossing Braille cells using a stylus, special embossing printer, or other device.") ),
    ("brd" , _("A person, family, or organization involved in broadcasting a resource to an audience via radio, television, webcast, etc.") ),
    ("cll" , _("Use for a person or organization who writes in an artistic hand, usually as a copyist and or engrosser.") ),
    ("ctg" , _("Use for a person or organization responsible for the creation of maps and other cartographic materials.") ),
    ("cas" , _("A person, family, or organization involved in manufacturing a resource by pouring a liquid or molten substance into a mold and leaving it to solidify to take the shape of the mold.") ),
    ("cns" , _("Use for a censor, bowdlerizer, expurgator, etc., official or private.") ),
    ("chr" , _("Use for a person or organization who composes or arranges dances or other movements (e.g., \"master of swords\") for a musical or dramatic presentation or entertainment.") ),
    ("cng" , _("Use for a person or organization who is in charge of the images captured for a motion picture film. The cinematographer works under the supervision of a director, and may also be referred to as director of photography. Do not confuse with videographer.") ),
    ("cli" , _("Use for a person or organization for whom another person or organization is acting.") ),
    ("cor" , _("A curator who lists or inventories the items in an aggregate work such as a collection of items or works.") ),
    ("col" , _("Use for a person or organization who has brought together material from various sources that has been arranged, described, and cataloged as a collection. A collector is neither the creator of the material nor a person to whom manuscripts in the collection may have been addressed.") ),
    ("clt" , _("Use for a person or organization responsible for the production of photographic prints from film or other colloid that has ink-receptive and ink-repellent surfaces.") ),
    ("clr" , _("A person or organization responsible for applying color to drawings, prints, photographs, maps, moving images, etc.") ),
    ("cmm" , _("Use for a person or organization who provides interpretation, analysis, or a discussion of the subject matter on a recording, motion picture, or other audiovisual medium.") ),
    ("cwt" , _("Use for a person or organization responsible for the commentary or explanatory notes about a text. For the writer of manuscript annotations in a printed book, use Annotator [ann].") ),
    ("com" , _("Use for a person or organization who produces a work or publication by selecting and putting together material from the works of various persons or bodies.") ),
    ("cpl" , _("Use for the party who applies to the courts for redress, usually in an equity proceeding.") ),
    ("cpt" , _("Use for a complainant who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding.") ),
    ("cpe" , _("Use for a complainant against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding.") ),
    ("cmp" , _("Use for a person or organization who creates a musical work, usually a piece of music in manuscript or printed form.") ),
    ("cmt" , _("Use for a person or organization responsible for the creation of metal slug, or molds made of other materials, used to produce the text and images in printed matter.") ),
    ("ccp" , _("Use for a person or organization responsible for the original idea on which a work is based, this includes the scientific author of an audio-visual item and the conceptor of an advertisement.") ),
    ("cnd" , _("Use for a person who directs a performing group (orchestra, chorus, opera, etc.) in a musical or dramatic presentation or entertainment.") ),
    ("con" , _("A person or organization responsible for documenting, preserving, or treating printed or manuscript material, works of art, artifacts, or other media.") ),
    ("csl" , _("Use for a person or organization relevant to a resource, who is called upon for professional advice or services in a specialized field of knowledge or training.") ),
    ("csp" , _("Use for a person or organization relevant to a resource, who is engaged specifically to provide an intellectual overview of a strategic or operational task and by analysis, specification, or instruction, to create or propose a cost-effective course of action or solution.") ),
    ("cos" , _("Use for the party who opposes, resists, or disputes, in a court of law, a claim, decision, result, etc.") ),
    ("cot" , _("Use for a contestant who takes an appeal from one court of law or jurisdiction to another to reverse the judgment.") ),
    ("coe" , _("Use for a contestant against whom an appeal is taken from one court of law or jurisdiction to another to reverse the judgment.") ),
    ("cts" , _("Use for the party defending a claim, decision, result, etc. being opposed, resisted, or disputed in a court of law.") ),
    ("ctt" , _("Use for a contestee who takes an appeal from one court or jurisdiction to another to reverse the judgment.") ),
    ("cte" , _("Use for a contestee against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment.") ),
    ("ctr" , _("Use for a person or organization relevant to a resource, who enters into a contract with another person or organization to perform a specific task.") ),
    ("ctb" , _("Use for a person or organization one whose work has been contributed to a larger work, such as an anthology, serial publication, or other compilation of individual works. Do not use if the sole function in relation to a work is as author, editor, compiler or translator.") ),
    ("cpc" , _("Use for a person or organization listed as a copyright owner at the time of registration. Copyright can be granted or later transferred to another person or organization, at which time the claimant becomes the copyright holder.") ),
    ("cph" , _("Use for a person or organization to whom copy and legal rights have been granted or transferred for the intellectual content of a work. The copyright holder, although not necessarily the creator of the work, usually has the exclusive right to benefit financially from the sale and use of the work to which the associated copyright protection applies.") ),
    ("crr" , _("Use for a person or organization who is a corrector of manuscripts, such as the scriptorium official who corrected the work of a scribe. For printed matter, use Proofreader.") ),
    ("crp" , _("Use for a person or organization who was either the writer or recipient of a letter or other communication.") ),
    ("cst" , _("Use for a person or organization who designs or makes costumes, fixes hair, etc., for a musical or dramatic presentation or entertainment.") ),
    ("cou" , _("A court governed by court rules, regardless of their official nature (e.g., laws, administrative regulations.)") ),
    ("crt" , _("A person, family, or organization contributing to a resource by preparing a court's opinions for publication.") ),
    ("cov" , _("Use for a person or organization responsible for the graphic design of a book cover, album cover, slipcase, box, container, etc. For a person or organization responsible for the graphic design of an entire book, use Book designer; for book jackets, use Bookjacket designer.") ),
    ("cre" , _("Use for a person or organization responsible for the intellectual or artistic content of a work.") ),
    ("cur" , _("Use for a person or organization responsible for conceiving and organizing an exhibition.") ),
    ("dnc" , _("Use for a person or organization who principally exhibits dancing skills in a musical or dramatic presentation or entertainment.") ),
    ("dtc" , _("Use for a person or organization that submits data for inclusion in a database or other collection of data.") ),
    ("dtm" , _("Use for a person or organization responsible for managing databases or other data sources.") ),
    ("dte" , _("Use for a person or organization to whom a book, manuscript, etc., is dedicated (not the recipient of a gift).") ),
    ("dto" , _("Use for the author of a dedication, which may be a formal statement or in epistolary or verse form.") ),
    ("dfd" , _("Use for the party defending or denying allegations made in a suit and against whom relief or recovery is sought in the courts, usually in a legal action.") ),
    ("dft" , _("Use for a defendant who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in a legal action.") ),
    ("dfe" , _("Use for a defendant against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in a legal action.") ),
    ("dgg" , _("Use for the organization granting a degree for which the thesis or dissertation described was presented.") ),
    ("dln" , _("Use for a person or organization executing technical drawings from others' designs.") ),
    ("dpc" , _("Use for an entity depicted or portrayed in a work, particularly in a work of art.") ),
    ("dpt" , _("Use for a person or organization placing material in the physical custody of a library or repository without transferring the legal title.") ),
    ("dsr" , _("Use for a person or organization responsible for the design if more specific codes (e.g., [bkd], [tyd]) are not desired.") ),
    ("drt" , _("Use for a person or organization who is responsible for the general management of a work or who supervises the production of a performance for stage, screen, or sound recording.") ),
    ("dis" , _("Use for a person who presents a thesis for a university or higher-level educational degree.") ),
    ("dbp" , _("A place from which a resource, e.g., a serial, is distributed.") ),
    ("dst" , _("Use for a person or organization that has exclusive or shared marketing rights for an item.") ),
    ("dnr" , _("Use for a person or organization who is the donor of a book, manuscript, etc., to its present owner. Donors to previous owners are designated as Former owner [fmo] or Inscriber [ins].") ),
    ("drm" , _("Use for a person or organization who prepares artistic or technical drawings.") ),
    ("dub" , _("Use for a person or organization to which authorship has been dubiously or incorrectly ascribed.") ),
    ("edt" , _("Use for a person or organization who prepares for publication a work not primarily his/her own, such as by elucidating text, adding introductory or other critical matter, or technically directing an editorial staff.") ),
    ("edc" , _("A person, family, or organization contributing to a collective or aggregate work by selecting and putting together works, or parts of works, by one or more creators. For compilations of data, information, etc., that result in new works, see compiler.") ),
    ("edm" , _("A person, family, or organization responsible for assembling, arranging, and trimming film, video, or other moving image formats, including both visual and audio aspects.") ),
    ("elg" , _("Use for a person responsible for setting up a lighting rig and focusing the lights for a production, and running the lighting at a performance.") ),
    ("elt" , _("Use for a person or organization who creates a duplicate printing surface by pressure molding and electrodepositing of metal that is then backed up with lead for printing.") ),
    ("eng" , _("Use for a person or organization that is responsible for technical planning and design, particularly with construction.") ),
    ("egr" , _("Use for a person or organization who cuts letters, figures, etc. on a surface, such as a wooden or metal plate, for printing.") ),
    ("etr" , _("Use for a person or organization who produces text or images for printing by subjecting metal, glass, or some other surface to acid or the corrosive action of some other substance.") ),
    ("evp" , _("A place where an event such as a conference or a concert took place.") ),
    ("exp" , _("Use for a person or organization in charge of the description and appraisal of the value of goods, particularly rare items, works of art, etc.") ),
    ("fac" , _("Use for a person or organization that executed the facsimile.") ),
    ("fld" , _("Use for a person or organization that manages or supervises the work done to collect raw data or do research in an actual setting or environment (typically applies to the natural and social sciences).") ),
    ("fmd" , _("A director responsible for the general management and supervision of a filmed performance.") ),
    ("fds" , _("A person, family, or organization involved in distributing a moving image resource to theatres or other distribution channels.") ),
    ("flm" , _("Use for a person or organization who is an editor of a motion picture film. This term is used regardless of the medium upon which the motion picture is produced or manufactured (e.g., acetate film, video tape).") ),
    ("fmp" , _("A producer responsible for most of the business aspects of a film.") ),
    ("fmk" , _("A person, family or organization responsible for creating an independent or personal film. A filmmaker is individually responsible for the conception and execution of all aspects of the film.") ),
    ("fpy" , _("Use for a person or organization who is identified as the only party or the party of the first part. In the case of transfer of right, this is the assignor, transferor, licensor, grantor, etc. Multiple parties can be named jointly as the first party.") ),
    ("frg" , _("Use for a person or organization who makes or imitates something of value or importance, especially with the intent to defraud.") ),
    ("fmo" , _("Use for a person or organization who owned an item at any time in the past. Includes those to whom the material was once presented. A person or organization giving the item to the present owner is designated as Donor [dnr].") ),
    ("fnd" , _("Use for a person or organization that furnished financial support for the production of the work.") ),
    ("gis" , _("Use for a person responsible for geographic information system (GIS) development and integration with global positioning system data.") ),
    ("hnr" , _("Use for a person or organization in memory or honor of whom a book, manuscript, etc. is donated.") ),
    ("hst" , _("Use for a person who is invited or regularly leads a program (often broadcast) that includes other guests, performers, etc. (e.g., talk show host).") ),
    ("his" , _("An organization hosting the event, exhibit, conference, etc., which gave rise to a resource, but having little or no responsibility for the content of the resource.") ),
    ("ilu" , _("Use for a person or organization responsible for the decoration of a work (especially manuscript material) with precious metals or color, usually with elaborate designs and motifs.") ),
    ("ill" , _("Use for a person or organization who conceives, and perhaps also implements, a design or illustration, usually to accompany a written text.") ),
    ("ins" , _("Use for a person who has written a statement of dedication or gift.") ),
    ("itr" , _("Use for a person or organization who principally plays an instrument in a musical or dramatic presentation or entertainment.") ),
    ("ive" , _("Use for a person or organization who is interviewed at a consultation or meeting, usually by a reporter, pollster, or some other information gathering agent.") ),
    ("ivr" , _("Use for a person or organization who acts as a reporter, pollster, or other information gathering agent in a consultation or meeting involving one or more individuals.") ),
    ("inv" , _("Use for a person or organization who first produces a particular useful item, or develops a new process for obtaining a known item or result.") ),
    ("isb" , _("A person, family or organization issuing a work, such as an official organ of the body.") ),
    ("jud" , _("A person who hears and decides on legal matters in court.") ),
    ("jug" , _("A jurisdiction governed by a law, regulation, etc., that was enacted by another jurisdiction.") ),
    ("lbr" , _("Use for an institution that provides scientific analyses of material samples.") ),
    ("ldr" , _("Use for a person or organization that manages or supervises work done in a controlled setting or environment.") ),
    ("lsa" , _("Use for a person or organization whose work involves coordinating the arrangement of existing and proposed land features and structures.") ),
    ("led" , _("Use to indicate that a person or organization takes primary responsibility for a particular activity or endeavor. Use with another relator term or code to show the greater importance this person or organization has regarding that particular role. If more than one relator is assigned to a heading, use the Lead relator only if it applies to all the relators.") ),
    ("len" , _("Use for a person or organization permitting the temporary use of a book, manuscript, etc., such as for photocopying or microfilming.") ),
    ("lil" , _("Use for the party who files a libel in an ecclesiastical or admiralty case.") ),
    ("lit" , _("Use for a libelant who takes an appeal from one ecclesiastical court or admiralty to another to reverse the judgment.") ),
    ("lie" , _("Use for a libelant against whom an appeal is taken from one ecclesiastical court or admiralty to another to reverse the judgment.") ),
    ("lel" , _("Use for a party against whom a libel has been filed in an ecclesiastical court or admiralty.") ),
    ("let" , _("Use for a libelee who takes an appeal from one ecclesiastical court or admiralty to another to reverse the judgment.") ),
    ("lee" , _("Use for a libelee against whom an appeal is taken from one ecclesiastical court or admiralty to another to reverse the judgment.") ),
    ("lbt" , _("Use for a person or organization who is a writer of the text of an opera, oratorio, etc.") ),
    ("lse" , _("Use for a person or organization who is an original recipient of the right to print or publish.") ),
    ("lso" , _("Use for person or organization who is a signer of the license, imprimatur, etc.") ),
    ("lgd" , _("Use for a person or organization who designs the lighting scheme for a theatrical presentation, entertainment, motion picture, etc.") ),
    ("ltg" , _("Use for a person or organization who prepares the stone or plate for lithographic printing, including a graphic artist creating a design directly on the surface from which printing will be done.") ),
    ("lyr" , _("Use for a person or organization who is the a writer of the text of a song.") ),
    ("mfp" , _("The place of manufacture (e.g., printing, duplicating, casting, etc.) of a resource in a published form.") ),
    ("mfr" , _("Use for a person or organization that makes an artifactual work (an object made or modified by one or more persons). Examples of artifactual works include vases, cannons or pieces of furniture.") ),
    ("mrb" , _("The entity responsible for marbling paper, cloth, leather, etc. used in construction of a resource.") ),
    ("mrk" , _("Use for a person or organization performing the coding of SGML, HTML, or XML markup of metadata, text, etc.") ),
    ("med" , _("A person held to be a channel of communication between the earthly world and a different world.") ),
    ("mdc" , _("Use for a person or organization primarily responsible for compiling and maintaining the original description of a metadata set (e.g., geospatial metadata set).") ),
    ("mte" , _("Use for a person or organization responsible for decorations, illustrations, letters, etc. cut on a metal surface for printing or decoration.") ),
    ("mtk" , _("A person, family, or organization responsible for recording the minutes of a meeting.") ),
    ("mod" , _("Use for a person who leads a program (often broadcast) where topics are discussed, usually with participation of experts in fields related to the discussion.") ),
    ("mon" , _("Use for a person or organization that supervises compliance with the contract and is responsible for the report and controls its distribution. Sometimes referred to as the grantee, or controlling agency.") ),
    ("mcp" , _("Use for a person who transcribes or copies musical notation.") ),
    ("msd" , _("Use for a person responsible for basic music decisions about a production, including coordinating the work of the composer, the sound editor, and sound mixers, selecting musicians, and organizing and/or conducting sound for rehearsals and performances.") ),
    ("mus" , _("Use for a person or organization who performs music or contributes to the musical content of a work when it is not possible or desirable to identify the function more precisely.") ),
    ("nrt" , _("Use for a person who is a speaker relating the particulars of an act, occurrence, or course of events.") ),
    ("osp" , _("A performer contributing to an expression of a work by appearing on screen in nonfiction moving image materials or introductions to fiction moving image materials to provide contextual or background information. Use when another term (e.g., Narrator, Host) is either not applicable or not desired.") ),
    ("opn" , _("Use for a person or organization responsible for opposing a thesis or dissertation.") ),
    ("orm" , _("Use for a person or organization responsible for organizing a meeting for which an item is the report or proceedings.") ),
    ("org" , _("Use for a person or organization performing the work, i.e., the name of a person or organization associated with the intellectual content of the work. This category does not include the publisher or personal affiliation, or sponsor except where it is also the corporate author.") ),
    ("oth" , _("Use for relator codes from other lists which have no equivalent in the MARC list or for terms which have not been assigned a code.") ),
    ("own" , _("Use for a person or organization that currently owns an item or collection.") ),
    ("pan" , _("A performer contributing to a resource by participating in a program (often broadcast) where topics are discussed, usually with participation of experts in fields related to the discussion.") ),
    ("ppm" , _("Use for a person or organization responsible for the production of paper, usually from wood, cloth, or other fibrous material.") ),
    ("pta" , _("Use for a person or organization that applied for a patent.") ),
    ("pth" , _("Use for a person or organization that was granted the patent referred to by the item.") ),
    ("pat" , _("Use for a person or organization responsible for commissioning a work. Usually a patron uses his or her means or influence to support the work of artists, writers, etc. This includes those who commission and pay for individual works.") ),
    ("prf" , _("Use for a person or organization who exhibits musical or acting skills in a musical or dramatic presentation or entertainment, if specific codes for those functions ([act], [dnc], [itr], [voc], etc.) are not used. If specific codes are used, [prf] is used for a person whose principal skill is not known or specified.") ),
    ("pma" , _("Use for an authority (usually a government agency) that issues permits under which work is accomplished.") ),
    ("pht" , _("Use for a person or organization responsible for taking photographs, whether they are used in their original form or as reproductions.") ),
    ("ptf" , _("Use for the party who complains or sues in court in a personal action, usually in a legal proceeding.") ),
    ("ptt" , _("Use for a plaintiff who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in a legal proceeding.") ),
    ("pte" , _("Use for a plaintiff against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in a legal proceeding.") ),
    ("plt" , _("Use for a person or organization responsible for the production of plates, usually for the production of printed images and/or text.") ),
    ("pra" , _("A person who is the faculty moderator of an academic disputation, normally proposing a thesis and participating in the ensuing disputation.") ),
    ("pre" , _("A person or organization mentioned in an 'X presents' credit for moving image materials and who is associated with production, finance, or distribution in some way. A vanity credit; in early years, normally the head of a studio.") ),
    ("prt" , _("Use for a person or organization who prints texts, whether from type or plates.") ),
    ("pop" , _("Use for a person or organization who prints illustrations from plates.") ),
    ("prm" , _("Use for a person or organization who makes a relief, intaglio, or planographic printing surface.") ),
    ("prc" , _("Use for a person or organization primarily responsible for performing or initiating a process, such as is done with the collection of metadata sets.") ),
    ("pro" , _("Use for a person or organization responsible for the making of a motion picture, including business aspects, management of the productions, and the commercial success of the work.") ),
    ("prn" , _("An organization that is responsible for financial, technical, and organizational management of a production for stage, screen, audio recording, television, webcast, etc.") ),
    ("prs" , _("A person or organization responsible for designing the overall visual appearance of a moving image production.") ),
    ("pmn" , _("Use for a person responsible for all technical and business matters in a production.") ),
    ("prd" , _("Use for a person or organization associated with the production (props, lighting, special effects, etc.) of a musical or dramatic presentation or entertainment.") ),
    ("prp" , _("The place of production (e.g., inscription, fabrication, construction, etc.) of a resource in an unpublished form.") ),
    ("prg" , _("Use for a person or organization responsible for the creation and/or maintenance of computer program design documents, source code, and machine-executable digital files and supporting documentation.") ),
    ("pdr" , _("Use for a person or organization with primary responsibility for all essential aspects of a project, or that manages a very large project that demands senior level responsibility, or that has overall responsibility for managing projects, or provides overall direction to a project manager.") ),
    ("pfr" , _("Use for a person who corrects printed matter. For manuscripts, use Corrector [crr].") ),
    ("prv" , _("A person or organization who produces, publishes, manufactures, or distributes a resource if specific codes are not desired (e.g. [mfr], [pbl].)") ),
    ("pup" , _("The place where a resource is published.") ),
    ("pbl" , _("Use for a person or organization that makes printed matter, often text, but also printed music, artwork, etc. available to the public.") ),
    ("pbd" , _("Use for a person or organization who presides over the elaboration of a collective work to ensure its coherence or continuity. This includes editors-in-chief, literary editors, editors of series, etc.") ),
    ("ppt" , _("Use for a person or organization who manipulates, controls, or directs puppets or marionettes in a musical or dramatic presentation or entertainment.") ),
    ("rdd" , _("A director responsible for the general management and supervision of a radio program.") ),
    ("rpc" , _("A producer responsible for most of the business aspects of a radio program.") ),
    ("rcp" , _("Use for a person or organization to whom correspondence is addressed.") ),
    ("rce" , _("Use for a person or organization who supervises the technical aspects of a sound or video recording session.") ),
    ("rce" , _("A person contributing to a resource by supervising the technical aspects of a sound or video recording session.") ),
    ("red" , _("Use for a person or organization who writes or develops the framework for an item without being intellectually responsible for its content.") ),
    ("ren" , _("Use for a person or organization who prepares drawings of architectural designs (i.e., renderings) in accurate, representational perspective to show what the project will look like when completed.") ),
    ("rpt" , _("Use for a person or organization who writes or presents reports of news or current events on air or in print.") ),
    ("rps" , _("Use for an agency that hosts data or material culture objects and provides services to promote long term, consistent and shared use of those data or objects.") ),
    ("rth" , _("Use for a person who directed or managed a research project.") ),
    ("rtm" , _("Use for a person who participated in a research project but whose role did not involve direction or management of it.") ),
    ("res" , _("Use for a person or organization responsible for performing research.") ),
    ("rsp" , _("Use for the party who makes an answer to the courts pursuant to an application for redress, usually in an equity proceeding.") ),
    ("rst" , _("Use for a respondent who takes an appeal from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding.") ),
    ("rse" , _("Use for a respondent against whom an appeal is taken from one court or jurisdiction to another to reverse the judgment, usually in an equity proceeding.") ),
    ("rpy" , _("Use for a person or organization legally responsible for the content of the published material.") ),
    ("rsg" , _("Use for a person or organization, other than the original choreographer or director, responsible for restaging a choreographic or dramatic work and who contributes minimal new content.") ),
    ("rsr" , _("A person, family, or organization responsible for the set of technical, editorial, and intellectual procedures aimed at compensating for the degradation of an item by bringing it back to a state as close as possible to its original condition.") ),
    ("rev" , _("Use for a person or organization responsible for the review of a book, motion picture, performance, etc.") ),
    ("rbr" , _("Use for a person or organization responsible for parts of a work, often headings or opening parts of a manuscript, that appear in a distinctive color, usually red.") ),
    ("sce" , _("Use for a person or organization who is the author of a motion picture screenplay.") ),
    ("sad" , _("Use for a person or organization who brings scientific, pedagogical, or historical competence to the conception and realization on a work, particularly in the case of audio-visual items.") ),
    ("scr" , _("Use for a person who is an amanuensis and for a writer of manuscripts proper. For a person who makes pen-facsimiles, use Facsimilist [fac].") ),
    ("scl" , _("Use for a person or organization who models or carves figures that are three-dimensional representations.") ),
    ("spy" , _("Use for a person or organization who is identified as the party of the second part. In the case of transfer of right, this is the assignee, transferee, licensee, grantee, etc. Multiple parties can be named jointly as the second party.") ),
    ("sec" , _("Use for a person or organization who is a recorder, redactor, or other person responsible for expressing the views of a organization.") ),
    ("sll" , _("A former owner of an item who sold that item to another owner.") ),
    ("std" , _("Use for a person or organization who translates the rough sketches of the art director into actual architectural structures for a theatrical presentation, entertainment, motion picture, etc. Set designers draw the detailed guides and specifications for building the set.") ),
    ("stg" , _("An entity in which the activity or plot of a work takes place, e.g. a geographic place, a time period, a building, an event.") ),
    ("sgn" , _("Use for a person whose signature appears without a presentation or other statement indicative of provenance. When there is a presentation statement, use Inscriber [ins].") ),
    ("sng" , _("Use for a person or organization who uses his/her/their voice with or without instrumental accompaniment to produce music. A performance may or may not include actual words.") ),
    ("sds" , _("Use for a person who produces and reproduces the sound score (both live and recorded), the installation of microphones, the setting of sound levels, and the coordination of sources of sound for a production.") ),
    ("spk" , _("Use for a person who participates in a program (often broadcast) and makes a formalized contribution or presentation generally prepared in advance.") ),
    ("spn" , _("Use for a person or organization that issued a contract or under the auspices of which a work has been written, printed, published, etc.") ),
    ("sgd" , _("A person or organization contributing to a stage resource through the overall management and supervision of a performance.") ),
    ("stm" , _("Use for a person who is in charge of everything that occurs on a performance stage, and who acts as chief of all crews and assistant to a director during rehearsals.") ),
    ("stn" , _("Use for an organization responsible for the development or enforcement of a standard.") ),
    ("str" , _("Use for a person or organization who creates a new plate for printing by molding or copying another printing surface.") ),
    ("stl" , _("Use for a person relaying a story with creative and/or theatrical interpretation.") ),
    ("sht" , _("Use for a person or organization that supports (by allocating facilities, staff, or other resources) a project, program, meeting, event, data objects, material culture objects, or other entities capable of support.") ),
    ("srv" , _("Use for a person or organization who does measurements of tracts of land, etc. to determine location, forms, and boundaries.") ),
    ("tch" , _("Use for a person who, in the context of a resource, gives instruction in an intellectual subject or demonstrates while teaching physical skills.") ),
    ("tcd" , _("Use for a person who is ultimately in charge of scenery, props, lights and sound for a production.") ),
    ("tld" , _("A director responsible for the general management and supervision of a television program.") ),
    ("tlp" , _("A producer responsible for most of the business aspects of a television program.") ),
    ("ths" , _("Use for a person under whose supervision a degree candidate develops and presents a thesis, mémoire, or text of a dissertation.") ),
    ("trc" , _("Use for a person who prepares a handwritten or typewritten copy from original material, including from dictated or orally recorded material. For makers of pen-facsimiles, use Facsimilist [fac].") ),
    ("trl" , _("Use for a person or organization who renders a text from one language into another, or from an older form of a language into the modern form.") ),
    ("tyd" , _("Use for a person or organization who designed the type face used in a particular item.") ),
    ("tyg" , _("Use for a person or organization primarily responsible for choice and arrangement of type used in an item. If the typographer is also responsible for other aspects of the graphic design of a book (e.g., Book designer [bkd]), codes for both functions may be needed.") ),
    ("uvp" , _("A place where a university that is associated with a resource is located, for example, a university where an academic dissertation or thesis was presented.") ),
    ("vdg" , _("Use for a person or organization in charge of a video production, e.g. the video recording of a stage production as opposed to a commercial motion picture. The videographer may be the camera operator or may supervise one or more camera operators. Do not confuse with cinematographer.") ),
    ("vac" , _("An actor contributing to a resource by providing the voice for characters in radio and audio productions and for animated characters in moving image works, as well as by providing voice overs in radio and television commercials, dubbed resources, etc.") ),
    ("wit" , _("Use for a person who verifies the truthfulness of an event or action.") ),
    ("wde" , _("Use for a person or organization who makes prints by cutting the image in relief on the end-grain of a wood block.") ),
    ("wdc" , _("Use for a person or organization who makes prints by cutting the image in relief on the plank side of a wood block.") ),
    ("wam" , _("Use for a person or organization who writes significant material which accompanies a sound recording or other audiovisual material.") ),
    ("wac" , _("A person, family, or organization contributing to an expression of a work by providing an interpretation or critical explanation of the original work.") ),
    ("wal" , _("A writer of words added to an expression of a musical work. For lyric writing in collaboration with a composer to form an original work, see lyricist.") ),
    ("wat" , _("A person, family, or organization contributing to a non-textual resource by providing text for the non-textual work (e.g., writing captions for photographs, descriptions of maps.)") ),
    ("win" , _("A person, family, or organization contributing to a resource by providing an introduction to the original work.") ),
    ("wpr" , _("A person, family, or organization contributing to a resource by providing a preface to the original work.") ),
    ("wst" , _("A person, family, or organization contributing to a resource by providing supplementary textual content (e.g., an introduction, a preface) to the original work.") )
])
